apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: guestbook
commonAnnotations:
  maintainer: mglynn@amazon.com
namePrefix: kustomize-
namespace: guestbook-kustomize

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
